### ISSUE TITLE
embedding struct tags

### ISSUE THREAD

**Issue by Frosin** [1pkg/gopium#22]
if click gopium pack:
![image](https://user-images.githubusercontent.com/31651395/113139553-efd89980-922f-11eb-8529-5e54336eea0c.png)
after:
![image](https://user-images.githubusercontent.com/31651395/113139598-fff07900-922f-11eb-872a-75ae72b8040b.png)
result: 
struct have invalid tags

**Comment by 1pkg** [comment]
@Frosin thank you for reporting, I will check it out.

**Comment by 1pkg** [comment]
Okay, it should be resolved now in v1.3.0 (hopefully). @Frosin please try it out.
The issue was long running issue about multiple embedded fields sorting for structure memory packing https://github.com/1pkg/gopium/issues/2. I figured, that just using naked types without extra indexes should be enough for embedded fields. Because go forbids having two embedded types with exact the same type hence type by itself should be unique identifier for embedded fields.

P.S.
@Frosin, I've even added your example to the tests https://github.com/1pkg/gopium/blob/master/tests/data/embedded/file.go#L16
https://github.com/1pkg/gopium/blob/master/walkers/wast_test.go#L360
Hope you don't mind about this.

**Comment by 1pkg** [comment]
Closing this as resolved.

**Comment by Frosin** [comment]
It works thanks
